### ISSUE TITLE
Handle special characters in passwords

### ISSUE THREAD

**Issue by dmfay** [mgutz/dalicious#1]
I use strong passwords containing special characters such as !#$ and so forth, which tend to do extremely bad things to connection strings unless they're encoded.

**Comment by dmfay** [comment]
@mgutz are dalicious and mygrate dead? We've been using the latter for some time now, and I quite like it; if you've moved on and don't want to deal with them anymore, I'd be interested in taking over maintenance.

**Comment by mgutz** [comment]
I added you as contributor to both. What is your npm account? I think I can add you there to update it.

**Comment by dmfay** [comment]
I'm dmfay there as well. Thanks!
